# Generated by Django 2.2.6 on 2019-10-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('relation', models.TextField(blank=True, null=True)),
                ('mobile', models.TextField(max_length=10)),
                ('address', models.TextField()),
                ('dob', models.DateTimeField()),
            ],
        ),
    ]
