# Generated by Django 2.2.6 on 2019-10-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_appointment', '0002_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
