# Generated by Django 2.2.6 on 2019-10-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_appointment', '0003_auto_20191020_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
